"""add aircraft groups

Revision ID: 1d308e7a2f98
Revises: 452daf180929
Create Date: 2026-09-16 16:25:38.578602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1d308e7a2f98'
down_revision: Union[str, Sequence[str], None] = '452daf180929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aircraft_registrations',
    sa.Column('registration', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('registration')
    )
    op.create_table('group_registrations',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['aircraft_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration'], ['aircraft_registrations.registration'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'registration')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_registrations')
    op.drop_table('aircraft_registrations')
    op.drop_table('aircraft_groups')
    # ### end Alembic commands ###
