"""initial schema

Revision ID: 452daf180929
Revises: 
Create Date: 2026-09-16 16:12:48.021910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452daf180929'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transponder_code', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=True),
    sa.Column('callsign', sa.Text(), nullable=True),
    sa.Column('registration', sa.Text(), nullable=True),
    sa.Column('aircraft_type', sa.Text(), nullable=True),
    sa.Column('position', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('barometric_altitude', sa.Text(), nullable=True),
    sa.Column('geometric_altitude', sa.Integer(), nullable=True),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('ground_speed_knots', sa.Float(), nullable=True),
    sa.Column('track', sa.Float(), nullable=True),
    sa.Column('true_heading', sa.Float(), nullable=True),
    sa.Column('squawk_code', sa.Text(), nullable=True),
    sa.Column('emergency_status', sa.Text(), nullable=True),
    sa.Column('aircraft_category', sa.Text(), nullable=True),
    sa.Column('navigation_qnh', sa.Float(), nullable=True),
    sa.Column('selected_altitude', sa.Integer(), nullable=True),
    sa.Column('navigation_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('navigation_integrity_category', sa.Integer(), nullable=True),
    sa.Column('radius_of_containment', sa.Integer(), nullable=True),
    sa.Column('seconds_since_position_update', sa.Float(), nullable=True),
    sa.Column('adsb_version', sa.Integer(), nullable=True),
    sa.Column('navigation_accuracy_position', sa.Integer(), nullable=True),
    sa.Column('navigation_accuracy_velocity', sa.Integer(), nullable=True),
    sa.Column('source_integrity_level', sa.Integer(), nullable=True),
    sa.Column('source_integrity_level_type', sa.Text(), nullable=True),
    sa.Column('system_design_assurance', sa.Integer(), nullable=True),
    sa.Column('alert_status', sa.Integer(), nullable=True),
    sa.Column('special_position_identification', sa.Integer(), nullable=True),
    sa.Column('multilateration_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('traffic_information_broadcast_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('seconds_since_last_message', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('extra_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('aircraft_positions_position_idx', 'aircraft_positions', ['position'], unique=False, postgresql_using='gist')
    op.create_index('aircraft_positions_recorded_at_idx', 'aircraft_positions', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('aircraft_positions_recorded_at_idx', table_name='aircraft_positions')
    op.drop_index('aircraft_positions_position_idx', table_name='aircraft_positions', postgresql_using='gist')
    op.drop_table('aircraft_positions')
    # ### end Alembic commands ###
