"""make group owner required

Revision ID: b28dbf48b67e
Revises: 33ca150e2c25
Create Date: 2026-09-16 23:52:43.944474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28dbf48b67e'
down_revision: Union[str, Sequence[str], None] = '33ca150e2c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft_groups', 'owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft_groups', 'owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
