"""make group owner required

Revision ID: b28dbf48b67e
Revises: 33ca150e2c25
Create Date: 2026-09-16 23:52:43.944474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28dbf48b67e'
down_revision: Union[str, Sequence[str], None] = '33ca150e2c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # Groups created before ownership existed have owner_user_id = NULL.
    # Assign them to a placeholder "system" user so the column can become
    # NOT NULL without losing data.
    orphan_count = bind.execute(
        sa.text("SELECT count(*) FROM aircraft_groups WHERE owner_user_id IS NULL")
    ).scalar()
    if orphan_count:
        system_user_id = bind.execute(
            sa.text("SELECT id FROM users WHERE username = 'system'")
        ).scalar()
        if system_user_id is None:
            system_user_id = bind.execute(
                sa.text(
                    "INSERT INTO users (username, password_hash) "
                    "VALUES ('system', '!') RETURNING id"
                )
            ).scalar()
        bind.execute(
            sa.text(
                "UPDATE aircraft_groups SET owner_user_id = :owner_id "
                "WHERE owner_user_id IS NULL"
            ),
            {"owner_id": system_user_id},
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft_groups', 'owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft_groups', 'owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
